### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by Immortal20032** [Saii1/Sentry-Craft#2]
1. Prémium rangú nem használhatja a veterán rang jogait (/heal, /feed)
2.Ha a bedrockot megütöm bal klikkel azt irja ki kreativ őrszem ezt nem használhatod kreativ módban holott túlélőben játszok.
3. a prémium rang nem használhatja  a /disguise wither-skeleton, cave spider mobokat pedig az van irva hogy igen.
4. ffa-ba be lehet menni saját szettel ha tpzel valakire vagy /backelsz .
5.Ha ffa ban pvp közben valamilyen úton módon bejutsz a "spawn" zónában ffan belül ott lehet sebezni azokat akik szintén igy jutottak be

**Comment by Immortal20032** [comment]
6. A prémium rang nemtud szinesen irni pedig ez is a jogai közt van

**Comment by Immortal20032** [comment]
Az 1. be a /feed et kiveszem

**Comment by Saii1** [comment]
Bedrock hiba javítva, feed jog van csak, A wither skeletont nem használhatja. A tábla hibás volt.
Ffa spawnban már nem lehet sebezni. A prémium már tud színesen írni.
