### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by Davidlordman** [Saii1/Sentry-Craft#3]
Aki kreatívban van az ki tud addolni másnak kaktuszt/cukornádat.
Úgy működik az egész, hogy felépít 1x1-ben egy magas oszlopot kaktuszból/cukornádból és kiüti az alját
Azok a blokkok amik a levegőben maradnak kiütve fognak hullani és ezt bármelyik player fel tudja venni.
(Ha minden igaz.)
~Agromash

**Comment by Saii1** [comment]
Köszi! Jutalmad: 508 SC
